version: "3"

services:
  redis:
    container_name: "redis"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
       - redis-data:/usr/local/etc/redis
    networks:
      - internal
    restart: unless-stopped

volumes:
  redis-data:
networks:
  internal:
    external: false